---
# illa-backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: illa-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: illa-backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: illa-backend
        infrastructure: fargate
    spec:
      containers:
      - image: docker.io/illasoft/illa-backend:latest
        imagePullPolicy: Always
        name: illa-backend
        ports:
        - containerPort: 9999
        env:
        - name: WEBSOCKET_SERVER_ADDRESS
          value: fast-try-ws.yourdomain.com
        - name: ILLA_PG_ADDR
          value: illa-database
        - name: WEBSOCKET_PORT
          value: "443"
        - name: WSS_ENABLED
          value: "true"
---
# illa-backend service
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: illa-backend
spec:
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: illa-backend
    infrastructure: fargate
