---
# illa-database deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: illa-database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: illa-database
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: illa-database
        infrastructure: fargate
    spec:
      containers:
      - image: docker.io/illasoft/illa-database:latest
        imagePullPolicy: Always
        name: illa-database
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
---
# illa-database service
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: illa-database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: illa-database
    infrastructure: fargate
