---
# illa-backend-ws deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: illa-backend-ws
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: illa-backend-ws
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: illa-backend-ws
        infrastructure: fargate
    spec:
      containers:
      - image: docker.io/illasoft/illa-backend-ws:latest
        imagePullPolicy: Always
        name: illa-backend-ws
        ports:
        - containerPort: 8000
        env:
        - name: WEBSOCKET_SERVER_ADDRESS
          value: fast-try-ws.yourdomain.com
        - name: ILLA_PG_ADDR
          value: illa-database
        - name: WEBSOCKET_PORT
          value: "8000"
---
# illa-backend-ws service
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: illa-backend-ws
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: illa-backend-ws
    infrastructure: fargate
